In [9]:
import numpy as np
import pandas as pd
arr=np.array([10,20,30,40,50])
print("array",arr)
print("mean",arr.mean())
print("Reshaped 2D \n",arr.reshape(5,1))
print("sliceed(index 1 to 3):",arr[1:4])
data={"name":["ravi","asha","mera","karan"],"marks":[88,72,91,65],"branch":["cse","ise","ece","cse"]}
df=pd.DataFrame(data)
print(df)
print("\nfirst 2 rows:\n",df.iloc[0:2])
print("\nmarks column:\n",df["marks"])
print("\nrows where marks >70:\n",df[df["marks"]>70])

array [10 20 30 40 50]
mean 30.0
Reshaped 2D
 [[10]
 [20]
 [30]
 [40]
 [50]]
sliceed(index 1 to 3): [20 30 40]
    name  marks branch
0   ravi     88    cse
1   asha     72    ise
2   mera     91    ece
3  karan     65    cse

first 2 rows:
    name  marks branch
0  ravi     88    cse
1  asha     72    ise

marks column:
 0    88
1    72
2    91
3    65
Name: marks, dtype: int64

rows where marks >70:
    name  marks branch
0  ravi     88    cse
1  asha     72    ise
2  mera     91    ece

In [3]:
import pandas as pd
df=pd.read_csv(r"C:\Users\user\Desktop\student_performance.csv")
df.head()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A

In [4]:
df.head()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A

In [5]:
df.tail()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
999995,999996,18.0,95.5,4.8,100.0,A
999996,999997,15.7,82.7,6.7,88.3,A
999997,999998,14.2,85.1,5.8,87.9,A
999998,999999,25.3,90.0,5.3,100.0,A
999999,1000000,18.3,84.6,4.1,100.0,A

In [7]:
df.shape

(1000000, 6)

In [8]:
df.columns

Index(['student_id', 'weekly_self_study_hours', 'attendance_percentage',
       'class_participation', 'total_score', 'grade'],
      dtype='str')

In [9]:
df.dtypes

student_id                   int64
weekly_self_study_hours    float64
attendance_percentage      float64
class_participation        float64
total_score                float64
grade                          str
dtype: object

In [10]:
df.info

<bound method DataFrame.info of         student_id  weekly_self_study_hours  attendance_percentage  \
0                1                     18.5                   95.6
1                2                     14.0                   80.0
2                3                     19.5                   86.3
3                4                     25.7                   70.2
4                5                     13.4                   81.9
...            ...                      ...                    ...
999995      999996                     18.0                   95.5
999996      999997                     15.7                   82.7
999997      999998                     14.2                   85.1
999998      999999                     25.3                   90.0
999999     1000000                     18.3                   84.6

        class_participation  total_score grade
0                       3.8         97.9     A
1                       2.5         83.9     B
2                       5.3        100.0     A
3                       7.0        100.0     A
4                       6.9         92.0     A
...                     ...          ...   ...
999995                  4.8        100.0     A
999996                  6.7         88.3     A
999997                  5.8         87.9     A
999998                  5.3        100.0     A
999999                  4.1        100.0     A

[1000000 rows x 6 columns]>

In [11]:
df.describe

<bound method NDFrame.describe of         student_id  weekly_self_study_hours  attendance_percentage  \
0                1                     18.5                   95.6
1                2                     14.0                   80.0
2                3                     19.5                   86.3
3                4                     25.7                   70.2
4                5                     13.4                   81.9
...            ...                      ...                    ...
999995      999996                     18.0                   95.5
999996      999997                     15.7                   82.7
999997      999998                     14.2                   85.1
999998      999999                     25.3                   90.0
999999     1000000                     18.3                   84.6

        class_participation  total_score grade
0                       3.8         97.9     A
1                       2.5         83.9     B
2                       5.3        100.0     A
3                       7.0        100.0     A
4                       6.9         92.0     A
...                     ...          ...   ...
999995                  4.8        100.0     A
999996                  6.7         88.3     A
999997                  5.8         87.9     A
999998                  5.3        100.0     A
999999                  4.1        100.0     A

[1000000 rows x 6 columns]>

In [12]:
df.isnull

<bound method DataFrame.isnull of         student_id  weekly_self_study_hours  attendance_percentage  \
0                1                     18.5                   95.6
1                2                     14.0                   80.0
2                3                     19.5                   86.3
3                4                     25.7                   70.2
4                5                     13.4                   81.9
...            ...                      ...                    ...
999995      999996                     18.0                   95.5
999996      999997                     15.7                   82.7
999997      999998                     14.2                   85.1
999998      999999                     25.3                   90.0
999999     1000000                     18.3                   84.6

        class_participation  total_score grade
0                       3.8         97.9     A
1                       2.5         83.9     B
2                       5.3        100.0     A
3                       7.0        100.0     A
4                       6.9         92.0     A
...                     ...          ...   ...
999995                  4.8        100.0     A
999996                  6.7         88.3     A
999997                  5.8         87.9     A
999998                  5.3        100.0     A
999999                  4.1        100.0     A

[1000000 rows x 6 columns]>

In [13]:
df.isnull().sum()

student_id                 0
weekly_self_study_hours    0
attendance_percentage      0
class_participation        0
total_score                0
grade                      0
dtype: int64

In [14]:
df.dropna()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A
...,...,...,...,...,...,...
999995,999996,18.0,95.5,4.8,100.0,A
999996,999997,15.7,82.7,6.7,88.3,A
999997,999998,14.2,85.1,5.8,87.9,A
999998,999999,25.3,90.0,5.3,100.0,A
999999,1000000,18.3,84.6,4.1,100.0,A

In [15]:
df.fillna(0)

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A
...,...,...,...,...,...,...
999995,999996,18.0,95.5,4.8,100.0,A
999996,999997,15.7,82.7,6.7,88.3,A
999997,999998,14.2,85.1,5.8,87.9,A
999998,999999,25.3,90.0,5.3,100.0,A
999999,1000000,18.3,84.6,4.1,100.0,A

In [16]:
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
999995    False
999996    False
999997    False
999998    False
999999    False
Length: 1000000, dtype: bool

In [17]:
df.duplicated().sum()

np.int64(0)

In [20]:
df.isnull().mean()*100

student_id                 0.0
weekly_self_study_hours    0.0
attendance_percentage      0.0
class_participation        0.0
total_score                0.0
grade                      0.0
dtype: float64

In [22]:
df.drop_duplicates()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A
...,...,...,...,...,...,...
999995,999996,18.0,95.5,4.8,100.0,A
999996,999997,15.7,82.7,6.7,88.3,A
999997,999998,14.2,85.1,5.8,87.9,A
999998,999999,25.3,90.0,5.3,100.0,A
999999,1000000,18.3,84.6,4.1,100.0,A

In [26]:
df["total_score"].mean()

np.float64(84.2838453)

In [27]:
df["total_score"].median()

np.float64(87.5)

In [28]:
df["total_score"].mode()

0    100.0
Name: total_score, dtype: float64

In [29]:
df["total_score"].var()

np.float64(238.17652523219314)

In [30]:
df["total_score"].std()

np.float64(15.432968775714967)

In [31]:
df["total_score"].min()

np.float64(9.4)

In [32]:
df["total_score"].max()

np.float64(100.0)

In [33]:
df["total_score"].count()

np.int64(1000000)

In [34]:
df["total_score"].unique()

array([ 97.9,  83.9, 100. ,  92. ,  97.5,  96.1,  69.8,  80.3,  66.4,
        72.5,  95.2,  60.9,  52.1,  73.5,  63. ,  75.4,  57.9,  79. ,
        76.3,  58.7,  68.3,  97.2,  68.4,  63.6,  89.2,  77.4,  82.6,
        71.9,  97.4,  61.6,  99.5,  50.1,  56.7,  84. ,  55.9,  89.6,
        78.7,  90.3,  71. ,  51.1,  82.7,  91. ,  92.7,  76.9,  91.9,
        89.5,  71.2,  81.9,  67.1,  69.9,  96.5,  80.4,  92.2,  83.6,
        78.8,  93.2,  84.5,  47.4,  90.8,  87.7,  91.7,  54.6,  81. ,
        79.5,  62.3,  64.9,  93.3,  98.4,  69.2,  93.9,  79.7,  86.6,
        72. ,  73.6,  67.3,  73.1,  63.9,  72.9,  73.4,  68.1,  86.1,
        83. ,  77.7,  93.6,  43.5,  93.8,  78.9,  84.2,  73.2,  95.4,
        92.1,  76.7,  74.1,  74.2,  74. ,  72.6,  74.8,  54.7,  50.6,
        86.8,  92.6,  97.3,  70.6,  54.8,  95. ,  58.2,  87.9,  86.2,
        58.9,  83.5,  90.2,  94.4,  85.4,  92.4,  79.6,  95.8,  75.8,
        72.2,  63.2,  66.2,  75.6,  75.5,  92.9,  84.7,  80.1,  75.9,
        52.2,  70.1,  89. ,  44.1,  80.5,  92.5,  65.4,  99.8,  53.2,
        85.9,  99.4,  70.2,  90.5,  83.7,  98.1,  95.5,  46.4,  63.1,
        87.4,  65.7,  54.2,  69.5,  81.5,  85.8,  53. ,  96. ,  81.2,
        55. ,  72.7,  55.6,  91.1,  80. ,  71.4,  74.7,  94.1,  38.9,
        60.4,  57.8,  63.8,  69.4,  68.7,  57.2,  69.3,  69.7,  90.1,
        78.1,  76.2,  69.6,  77.6,  82.4,  89.1,  43.9,  54.5,  62.1,
        85.6,  80.8,  71.6,  74.5,  87.5,  89.9,  94.9,  62.9,  81.1,
        87.6,  88.1,  77.1,  90.6,  95.9,  99.6,  82.2,  79.8,  94.6,
        84.1,  85.3,  87.2,  98.6,  41.3,  81.3,  97.8,  99.9,  80.6,
        97. ,  89.4,  59. ,  56.9,  79.9,  91.5,  87.3,  88.3,  68.8,
        94.7,  76.4,  72.1,  85.1,  82.5,  77.5,  96.4,  76.5,  88.7,
        33.8,  97.6,  54.1,  58.6,  67.2,  67.8,  88.6,  88.5,  54.3,
        96.3,  89.8,  81.8,  47. ,  54.4,  76. ,  92.8,  75.3,  88.4,
        45.8,  98.2,  66.9,  49.3,  93.4,  51.9,  94. ,  96.2,  85.2,
        99.2,  72.3,  66. ,  60. ,  82.1,  83.4,  80.2,  78.5,  67.7,
        68.5,  87.8,  85.5,  72.8,  63.5,  56.8,  75.2,  64.6,  80.7,
        80.9,  94.3,  65.8,  66.1,  90.7,  63.3,  79.1,  88.2,  99.3,
        55.1,  43. ,  37.8,  65.3,  87. ,  98.9,  86.5,  82.8,  61.8,
        83.8,  61.9,  58.1,  86. ,  93.7,  91.3,  84.9,  91.4,  52.3,
        99.1,  96.7,  89.7,  71.1,  78.3,  49.8,  44.5,  90. ,  86.9,
        78.6,  94.8,  98.8,  84.4,  34.5,  97.7,  51.8,  70.5,  74.6,
        83.2,  51.6,  95.1,  66.7,  96.8,  50.5,  77.2,  61.4,  78.4,
        46.6,  81.6,  48.3,  74.4,  67. ,  92.3,  70.9,  62.5,  91.8,
        62. ,  85. ,  70.7,  71.3,  98.3,  58. ,  93.5,  73.7,  89.3,
        51.4,  75.1,  62.2,  60.5,  65.2,  71.7,  77.3,  64.4,  77. ,
        88.8,  55.3,  86.3,  87.1,  65. ,  65.5,  94.2,  73.3,  77.9,
        79.2,  79.3,  54.9,  51.7,  59.6,  53.3,  62.4,  44.7,  59.9,
        82.3,  67.9,  60.3,  35.8,  68.2,  91.6,  81.7,  76.8,  94.5,
        64.1,  93.1,  79.4,  98.7,  50.2,  95.7,  75.7,  68.9,  71.5,
        53.6,  93. ,  96.6,  86.4,  50.4,  60.7,  98. ,  62.8,  66.3,
        73.9,  49.4,  70. ,  49.9,  68.6,  96.9,  90.4,  72.4,  47.6,
        75. ,  69.1,  52.7,  81.4,  48.5,  64.3,  98.5,  85.7,  84.8,
        95.3,  59.8,  40.6,  68. ,  88. ,  97.1,  55.4,  43.6,  82.9,
        74.3,  40.1,  64.2,  95.6,  53.1,  53.4,  52.9,  67.4,  74.9,
        46.7,  50.3,  55.8,  88.9,  44.8,  66.5,  83.1,  66.8,  78.2,
        56.1,  73.8,  77.8,  49.2,  34.7,  90.9,  70.4,  63.4,  48.8,
        57.5,  49. ,  78. ,  84.3,  62.6,  53.8,  57.1,  52.6,  44.6,
        58.8,  64.5,  56. ,  40.7,  61.3,  65.6,  36.6,  99. ,  59.3,
        42.2,  76.1,  59.2,  60.1,  67.5,  73. ,  45.7,  44.4,  51.5,
        51.2,  45.1,  53.7,  45.4,  52.5,  61.1,  91.2,  60.6,  14.6,
        55.2,  46.1,  57.4,  45.2,  62.7,  64.8,  42.3,  76.6,  34.9,
        82. ,  63.7,  56.5,  58.5,  70.8,  35.2,  99.7,  24.3,  65.9,
        46.2,  67.6,  44. ,  83.3,  57.7,  70.3,  86.7,  53.9,  64. ,
        61.7,  34.4,  59.4,  36. ,  48.9,  43.8,  59.1,  47.3,  69. ,
        66.6,  50. ,  57. ,  43.2,  84.6,  65.1,  47.7,  50.8,  60.8,
        61.2,  60.2,  36.8,  42.6,  41.7,  37.1,  40.2,  52.4,  59.7,
        42.4,  56.3,  48.1,  39. ,  28.2,  48. ,  64.7,  39.2,  42.1,
        38.5,  46.8,  30.2,  49.1,  33.6,  59.5,  48.6,  48.4,  36.4,
        47.8,  58.4,  45.6,  31. ,  52.8,  45.9,  44.9,  32.6,  50.7,
        39.7,  32.1,  42.8,  41.4,  47.9,  57.6,  61.5,  47.2,  40.3,
        46. ,  56.2,  71.8,  38.4,  56.6,  46.9,  38.6,  39.9,  56.4,
        41.5,  41.1,  43.7,  53.5,  44.2,  37.9,  61. ,  57.3,  50.9,
        33.3,  43.1,  54. ,  34.2,  46.5,  49.5,  35.1,  29.9,  42.7,
        37. ,  41.9,  29.5,  36.1,  40.4,  58.3,  39.3,  48.7,  39.6,
        35.9,  40.5,  51. ,  34.3,  47.5,  35.4,  35.7,  45.3,  37.4,
        28.4,  31.6,  46.3,  30.9,  43.3,  38.7,  38.1,  34.1,  42. ,
        37.2,  52. ,  35. ,  47.1,  32.9,  37.6,  45.5,  55.5,  36.7,
        40.9,  55.7,  49.6,  34. ,  37.7,  32.5,  36.2,  39.4,  34.6,
        45. ,  33.4,  39.8,  32.7,  44.3,  30.1,  31.2,  36.5,  51.3,
        31.4,  30.7,  33. ,  41.8,  31.9,  31.8,  31.5,  33.2,  40.8,
        27.6,  40. ,  41.6,  39.1,  37.5,  48.2,  41.2,  26.2,  35.6,
        42.5,  36.9,  49.7,  38.2,  32.4,  30.5,  29.6,  37.3,  25.4,
        43.4,  35.3,  42.9,  33.9,  35.5,  33.1,  34.8,  29.3,  30.8,
        28.5,  26.3,  38.3,  28.1,  41. ,  25.9,  19.5,  18.1,  32. ,
        31.7,  39.5,  29.4,  27.5,  38. ,  27.2,  38.8,  26.4,  29.8,
        33.5,  32.8,  24.6,  27.3,  30. ,  32.3,  27.1,  30.6,  22.6,
        28. ,  23.9,  28.6,  24.5,  36.3,  28.3,  32.2,  26.1,  28.8,
        24.1,  29.2,  23.1,  14.7,  22. ,  31.3,  30.3,  24.7,  25.3,
        21.6,  25.1,  27.9,  25.8,  27.4,  27.7,  21.1,  19.3,  21.9,
        17.7,  22.9,  30.4,  23.4,  26.6,  23.7,  29.1,  29.7,   9.4,
        23.2,  28.9,  33.7,  23. ,  14.4,  25.5,  21.7,  26.8,  31.1,
        27.8,  15.7,  24.9,  24.8,  28.7,  22.7,  24. ,  19.9,  27. ,
        29. ,  24.4,  18.3,  23.6,  25.7,  22.4,  26.5,  25.6,  25. ,
        26.7,  21.2,  16.9,  26. ,  20.5,  20.7,  17.9,  22.3,  19.2,
        20.9,  26.9,  23.3,  19. ,  20.1,  18.9,  12.2,  16.4,  20.6,
        16.2,  18.5,  21.8,  25.2,  15.9,  23.5,  18.6,  17.3,  22.1,
        22.8,  24.2,  23.8,  21.4,  20.2,  22.2,  20. ,  19.6,  18.4,
        21. ,  19.4,  18.2,  19.8,  22.5])

In [35]:
df["total_score"].nunique()

824

In [36]:
df["total_score"].value_counts()

total_score
100.0    268121
86.0       2051
88.7       2037
88.5       2036
86.2       2035
          ...
20.0          1
18.4          1
19.4          1
18.2          1
22.5          1
Name: count, Length: 824, dtype: int64

In [37]:
df["total_score"]

0          97.9
1          83.9
2         100.0
3         100.0
4          92.0
          ...
999995    100.0
999996     88.3
999997     87.9
999998    100.0
999999    100.0
Name: total_score, Length: 1000000, dtype: float64

In [45]:
df[df["total_score"]>30]

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A
...,...,...,...,...,...,...
999995,999996,18.0,95.5,4.8,100.0,A
999996,999997,15.7,82.7,6.7,88.3,A
999997,999998,14.2,85.1,5.8,87.9,A
999998,999999,25.3,90.0,5.3,100.0,A
999999,1000000,18.3,84.6,4.1,100.0,A

In [46]:
df.sort_values("total_score")

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
114309,114310,0.0,72.5,3.8,9.4,F
384794,384795,0.0,84.0,5.0,12.2,F
128034,128035,0.0,74.4,6.9,14.4,F
430442,430443,1.5,70.5,5.0,14.6,F
2118,2119,0.0,79.8,2.7,14.6,F
...,...,...,...,...,...,...
999995,999996,18.0,95.5,4.8,100.0,A
999998,999999,25.3,90.0,5.3,100.0,A
20,21,25.3,89.3,6.4,100.0,A
17,18,17.2,74.0,8.1,100.0,A
999999,1000000,18.3,84.6,4.1,100.0,A

In [47]:
df.rename(columns={"total_score":"total_score"})

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A
...,...,...,...,...,...,...
999995,999996,18.0,95.5,4.8,100.0,A
999996,999997,15.7,82.7,6.7,88.3,A
999997,999998,14.2,85.1,5.8,87.9,A
999998,999999,25.3,90.0,5.3,100.0,A
999999,1000000,18.3,84.6,4.1,100.0,A

In [50]:
df.drop("total_score", axis=1)

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,grade
0,1,0.38,95.6,3.8,A
1,2,0.25,80.0,2.5,B
2,3,0.53,86.3,5.3,A
3,4,0.70,70.2,7.0,A
4,5,0.69,81.9,6.9,A
...,...,...,...,...,...
999995,999996,0.48,95.5,4.8,A
999996,999997,0.67,82.7,6.7,A
999997,999998,0.58,85.1,5.8,A
999998,999999,0.53,90.0,5.3,A
999999,1000000,0.41,84.6,4.1,A

In [51]:
df.groupby("student_id")

In [52]:
df.groupby("student_id")["class_participation"].mean()

student_id
1          3.8
2          2.5
3          5.3
4          7.0
5          6.9
          ...
999996     4.8
999997     6.7
999998     5.8
999999     5.3
1000000    4.1
Name: class_participation, Length: 1000000, dtype: float64